// src/views/Home.vue
<template>
  <div>
    <HomePage
      v-if="currentView === 'home'"
      @check-compatibility="handleCheckCompatibility"
    />
    <CompatibilityResult
      v-else-if="currentView === 'result' && myZodiac && partnerZodiac"
      :my-zodiac="myZodiac"
      :partner-zodiac="partnerZodiac"
      @back="handleBack"
    />
  </div>
</template>

<script setup lang="ts">
import CompatibilityResult from "@/components/CompatibilityResult.vue";
import HomePage from "@/components/HomePage.vue";
import { type ZodiacAnimal } from "@/lib/zodiac";
import { ref } from "vue";

const currentView = ref<"home" | "result">("home");
const myZodiac = ref<ZodiacAnimal | null>(null);
const partnerZodiac = ref<ZodiacAnimal | null>(null);

const handleCheckCompatibility = (my: ZodiacAnimal, partner: ZodiacAnimal) => {
  myZodiac.value = my;
  partnerZodiac.value = partner;
  currentView.value = "result";
};

const handleBack = () => {
  currentView.value = "home";
};
</script>

<style scoped>
/* 추가 스타일이 필요한 경우 여기에 작성 */
</style>

// client/src/pages/Home.tsx
import { useState } from "react";
import HomePage from "@/components/HomePage";
import ResultPage from "@/components/ResultPage";
import { type ZodiacAnimal } from "@/lib/zodiac";

export default function Home() {
  const [currentView, setCurrentView] = useState<"home" | "result">("home");
  const [myZodiac, setMyZodiac] = useState<ZodiacAnimal | null>(null);
  const [partnerZodiac, setPartnerZodiac] = useState<ZodiacAnimal | null>(null);

  const handleCheckCompatibility = (my: ZodiacAnimal, partner: ZodiacAnimal) => {
    setMyZodiac(my);
    setPartnerZodiac(partner);
    setCurrentView("result");
  };

  const handleBack = () => {
    setCurrentView("home");
  };

  if (currentView === "result" && myZodiac && partnerZodiac) {
    return (
      <ResultPage
        myZodiac={myZodiac}
        partnerZodiac={partnerZodiac}
        onBack={handleBack}
      />
    );
  }

  return <HomePage onCheckCompatibility={handleCheckCompatibility} />;
}
