// src/components/ZodiacSelector.vue
<template>
  <div class="animal-grid">
    <div
      v-for="animal in zodiacAnimals"
      :key="animal.id"
      class="animal-item"
      :class="{ selected: selectedZodiac?.id === animal.id }"
      @click="handleSelect(animal)"
      :data-testid="`button-zodiac-${animal.id}`"
    >
      <img :src="animal.image" :alt="animal.name" class="animal-icon" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { zodiacAnimals, type ZodiacAnimal } from "@/lib/zodiac";

interface Props {
  selectedZodiac?: ZodiacAnimal;
  onSelect: (zodiac: ZodiacAnimal) => void;
  title: string;
}

const props = defineProps<Props>();

const handleSelect = (animal: ZodiacAnimal) => {
  console.log(`${animal.name} selected`);
  props.onSelect(animal);
};
</script>

// client/src/components/examples/ZodiacSelector.tsx
import ZodiacSelector from '../ZodiacSelector';
import { zodiacAnimals } from '@/lib/zodiac';
import { useState } from 'react';
import type { ZodiacAnimal } from '@/lib/zodiac';

export default function ZodiacSelectorExample() {
  const [selected, setSelected] = useState<ZodiacAnimal>(zodiacAnimals[0]);
  
  return (
    <div className="max-w-md mx-auto p-4">
      <ZodiacSelector
        selectedZodiac={selected}
        onSelect={setSelected}
        title="내 띠 선택"
      />
    </div>
  );
}
