// client/src/components/CompatibilityResult.tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { type ZodiacAnimal, getCompatibilityMessage, getCompatibilityScore } from "@/lib/zodiac";
import { ArrowLeft, Heart } from "lucide-react";
import { useEffect, useState } from "react";

interface CompatibilityResultProps {
  myZodiac: ZodiacAnimal;
  partnerZodiac: ZodiacAnimal;
  onBack: () => void;
}

export default function CompatibilityResult({ myZodiac, partnerZodiac, onBack }: CompatibilityResultProps) {
  const finalScore = getCompatibilityScore(myZodiac, partnerZodiac);
  const [animatedScore, setAnimatedScore] = useState(0);
  const [progressValue, setProgressValue] = useState(0);
  const [showMessage, setShowMessage] = useState(false);
  const message = getCompatibilityMessage(finalScore);
  
  useEffect(() => {
    const duration = 2000; // 2초 동안 애니메이션
    const steps = 60; // 60프레임
    const stepDuration = duration / steps;
    const scoreIncrement = finalScore / steps;
    const progressIncrement = finalScore / steps;
    
    let currentStep = 0;
    
    const timer = setInterval(() => {
      currentStep++;
      const newScore = Math.min(Math.floor(scoreIncrement * currentStep), finalScore);
      const newProgress = Math.min(progressIncrement * currentStep, finalScore);
      
      setAnimatedScore(newScore);
      setProgressValue(newProgress);
      
      if (currentStep >= steps) {
        clearInterval(timer);
        setAnimatedScore(finalScore);
        setProgressValue(finalScore);
        // 점수 애니메이션 완료 후 0.5초 뒤에 메시지 표시
        setTimeout(() => {
          setShowMessage(true);
        }, 500);
      }
    }, stepDuration);
    
    return () => clearInterval(timer);
  }, [finalScore]);
  
  const getScoreColor = (score: number) => {
    if (score >= 81) return "text-blue-600 dark:text-blue-400";  // 81-100: 파란색
    if (score >= 61) return "text-green-600 dark:text-green-400"; // 61-80: 초록색
    if (score >= 41) return "text-yellow-600 dark:text-yellow-400"; // 41-60: 노란색
    return "text-red-600 dark:text-red-400"; // 0-40: 빨간색
  };

  const getProgressColor = (score: number) => {
    if (score >= 81) return "bg-blue-500";    // 81-100: 파란색
    if (score >= 61) return "bg-green-500";   // 61-80: 초록색
    if (score >= 41) return "bg-yellow-500";  // 41-60: 노란색
    return "bg-red-500"; // 0-40: 빨간색
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6" data-testid="container-compatibility-result">
      <Card className="text-center">
        <CardHeader>
          <CardTitle className="flex items-center justify-center gap-2 text-2xl" data-testid="text-result-title">
            <Heart className="text-primary" />
            궁합 결과
            <Heart className="text-primary" />
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* 띠 표시 */}
          <div className="flex items-center justify-center gap-8">
            <div className="text-center" data-testid="display-my-zodiac">
              <div className="text-4xl mb-2" role="img" aria-label={myZodiac.name}>
                <img 
                  src={myZodiac.image} 
                  alt={myZodiac.name}
                  className="w-[180px] h-[180px] object-contain mx-auto"
                />
              </div>
              <p className="font-medium">{myZodiac.name}띠</p>
              <p className="text-sm text-muted-foreground">나</p>
            </div>
            
            <div className="flex items-center text-2xl text-primary">
              <Heart className="animate-pulse" />
            </div>
            
            <div className="text-center" data-testid="display-partner-zodiac">
              <div className="text-4xl mb-2" role="img" aria-label={partnerZodiac.name}>
                <img 
                  src={partnerZodiac.image} 
                  alt={partnerZodiac.name}
                  className="w-[180px] h-[180px] object-contain mx-auto"
                />
              </div>
              <p className="font-medium">{partnerZodiac.name}띠</p>
              <p className="text-sm text-muted-foreground">상대방</p>
            </div>
          </div>
          
          {/* 점수 표시 */}
          <div className="space-y-4">
            <div className="text-center">
              <div className={`text-6xl font-bold ${getScoreColor(animatedScore)}`} data-testid="text-compatibility-score">
                {animatedScore}점
              </div>
              <div className="mt-4">
                <div className="w-full bg-gray-200 rounded-full h-3">
                  <div 
                    className={`h-3 rounded-full transition-all duration-100 ${getProgressColor(animatedScore)}`}
                    style={{ width: `${progressValue}%` }}
                  />
                </div>
              </div>
            </div>
            
            {showMessage && (
              <Card className="bg-muted animate-in fade-in duration-500" data-testid="compatibility-message-card">
                <CardContent className="p-4">
                  <p className="text-lg leading-relaxed" data-testid="text-compatibility-message">
                    {message}
                  </p>
                </CardContent>
              </Card>
            )}
          </div>
        </CardContent>
      </Card>
      
      <div className="text-center">
        <Button
          onClick={() => {
            console.log('Back button clicked');
            onBack();
          }}
          variant="outline"
          size="lg"
          className="gap-2"
          data-testid="button-back"
        >
          <ArrowLeft className="w-4 h-4" />
          다시 확인하기
        </Button>
      </div>
    </div>
  );
}

// src/components/CompatibilityResult.vue
<template>
  <div class="result-container" data-testid="container-compatibility-result">
    <!-- 헤더 -->
    <div class="result-header">
      <h1 class="result-title">💖 {{ $t("ui.resultTitle") }} 💖</h1>
    </div>

    <!-- 결과 카드 -->
    <div class="result-card">
      <!-- 선택된 띠들 -->
      <div class="result-content">
        <div class="result-animal">
          <img :src="myZodiac.image" :alt="$t(`zodiac.${myZodiac.id}`)" />
          <h3>{{ $t(`zodiac.${myZodiac.id}`) }}</h3>
        </div>

        <div class="result-score">
          <div class="score-icon">💖</div>
          <div class="score-number" :class="getScoreColorClass(animatedScore)">
            {{ animatedScore }}{{ $t("ui.yearSuffix") }}
          </div>
        </div>

        <div class="result-animal">
          <img
            :src="partnerZodiac.image"
            :alt="$t(`zodiac.${partnerZodiac.id}`)"
          />
          <h3>{{ $t(`zodiac.${partnerZodiac.id}`) }}</h3>
        </div>
      </div>

      <!-- 점수 바 -->
      <div class="result-progress">
        <div
          class="result-progress-bar"
          :class="getScoreColorClass(animatedScore)"
          :style="{ width: `${animatedScore}%` }"
        ></div>
      </div>

      <!-- 궁합 메시지 -->
      <div
        class="result-message"
        :class="{
          'fade-in': showMessage,
          'has-content': showMessage,
        }"
      >
        {{ showMessage ? message : "" }}
      </div>

      <!-- 뒤로가기 버튼 -->
      <button
        @click="onBack"
        class="back-btn"
        :class="{ 'fade-in': showButton }"
        :disabled="!showButton"
      >
        ← {{ $t("ui.checkAgain") }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  getCompatibilityMessageKey,
  getCompatibilityScore,
  type ZodiacAnimal,
} from "@/lib/zodiac";
import { computed, onMounted, ref } from "vue";
import { useI18n } from "vue-i18n";

interface Props {
  myZodiac: ZodiacAnimal;
  partnerZodiac: ZodiacAnimal;
  onBack: () => void;
}

const props = defineProps<Props>();
const { t } = useI18n();

// 궁합 점수 계산
const score = computed(() => {
  return getCompatibilityScore(props.myZodiac, props.partnerZodiac);
});

// 애니메이션용 점수
const animatedScore = ref(0);

// 궁합 메시지
const message = computed(() => {
  const messageKey = getCompatibilityMessageKey(score.value);
  return t(messageKey);
});

// 점수에 따른 색상 (동적)
const getScoreColorClass = (currentScore: number) => {
  if (currentScore >= 90) return "blue";
  if (currentScore >= 80) return "green";
  if (currentScore >= 70) return "yellow";
  if (currentScore >= 60) return "yellow";
  return "red";
};

// 애니메이션 상태
const showMessage = ref(false);
const showButton = ref(false);

// 점수 카운트 애니메이션
const animateScore = () => {
  const targetScore = score.value;
  const duration = 2000; // 2초
  const steps = 60; // 60프레임
  const stepTime = duration / steps;
  const increment = targetScore / steps;

  let currentStep = 0;

  const timer = setInterval(() => {
    currentStep++;
    animatedScore.value = Math.min(
      Math.floor(increment * currentStep),
      targetScore
    );

    if (currentStep >= steps) {
      clearInterval(timer);
      animatedScore.value = targetScore;

      // 점수 애니메이션 완료 후 0.5초 뒤 메시지 표시
      setTimeout(() => {
        showMessage.value = true;

        // 메시지 표시 후 버튼 표시
        setTimeout(() => {
          showButton.value = true;
        }, 500);
      }, 500); // 0.5초로 변경
    }
  }, stepTime);
};

// 컴포넌트 마운트 시 애니메이션 시작
onMounted(() => {
  setTimeout(() => {
    animateScore();
  }, 500); // 0.5초 후 시작
});
</script>
