// src/components/Zodiac-Selector.vue
<template>
  <div class="animal-grid">
    <div
      v-for="(animal, index) in displayAnimals"
      :key="`${animal.id}-${index}`"
      class="animal-item"
      :class="{ selected: selectedZodiac?.id === animal.id }"
      @click="handleSelect(animal)"
      :data-testid="`button-zodiac-${animal.id}`"
    >
      <img :src="animal.image" :alt="$t(`zodiac.${animal.id}`)" class="animal-icon" />
      <div class="animal-name">{{ $t(`zodiac.${animal.id}`) }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { zodiacAnimals, type ZodiacAnimal } from "@/lib/zodiac";
import { computed } from "vue";
import { useI18n } from "vue-i18n";

interface Props {
  selectedZodiac?: ZodiacAnimal;
  onSelect: (zodiac: ZodiacAnimal) => void;
  title: string;
}

const props = defineProps<Props>();
const { t } = useI18n();

// 모바일에서 스크롤을 위한 동물 배열 (반복 없음)
const displayAnimals = computed(() => {
  return zodiacAnimals;
});

const handleSelect = (animal: ZodiacAnimal) => {
  console.log(`${animal.name} selected`);
  props.onSelect(animal);
};
</script>

// client/src/components/ZodiacSelector.tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { zodiacAnimals, type ZodiacAnimal } from "@/lib/zodiac";

interface ZodiacSelectorProps {
  selectedZodiac?: ZodiacAnimal;
  onSelect: (zodiac: ZodiacAnimal) => void;
  title: string;
}

export default function ZodiacSelector({ selectedZodiac, onSelect, title }: ZodiacSelectorProps) {
  return (
    <Card data-testid="card-zodiac-selector">
      <CardContent className="p-6">
        <h3 className="text-lg font-semibold mb-4 text-center" data-testid="text-title">
          {title}
        </h3>
        <div className="grid grid-cols-3 sm:grid-cols-4 gap-3">
          {zodiacAnimals.map((animal) => (
            <Button
              key={animal.id}
              variant={selectedZodiac?.id === animal.id ? "default" : "outline"}
              className="h-auto py-3 flex flex-col gap-1 hover-elevate"
              onClick={() => {
                console.log(`${animal.name} selected`);
                onSelect(animal);
              }}
              data-testid={`button-zodiac-${animal.id}`}
            >
              <img 
                src={animal.image} 
                alt={animal.name}
                className="w-10 h-10 object-cover rounded-md"
                data-testid={`img-zodiac-${animal.id}`}
                loading="lazy"
                decoding="async"
              />
              <span className="text-xs font-medium">{animal.name}</span>
            </Button>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
